### ISSUE TITLE
Unable to create model 

### ISSUE THREAD

**Issue by farouk2u** [AbderrahimSoubaiElidrissi/create-node-app#1]
(node:17346) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './templates/node/model-ts.tpl'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at createFile (/usr/local/lib/node_modules/@soubai/node-cli/lib/creator.js:81:19)
    at inquirer.prompt.then.answer (/usr/local/lib/node_modules/@soubai/node-cli/lib/creator.js:126:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by soub4i** [comment]
Hi Farouk 
Thank you for opening this
Fix by this https://github.com/AbderrahimSoubaiElidrissi/create-node-app/commit/3cd29bae890ac6da1a327e039f0c684906413681
